### DISCUSSION TITLE
Having issue in looking at details of a new or old certificate discovery record, after I have upgraded to v2.13.0

### DISCUSSION THREAD

**Discussion by iftikharahmd** [OmniTrustILM/ilm#42] [Q&A]
I recently upgraded my installation of Czertainly from v2.11.0-1 to v2.13.0.  The upgrade process went smooth, but I get a white page when I try to Discoveries and click on one of the old or a newly executed discovery.  I also tried to Inspect the page and saw that there is a 401 unauthorized error.  This is strange because I am logged in using admin account which is part of superadmin role with access to everything.  It seems something wrong has happened to the user / role permissions, during the upgrade process.  Image is attached for reference.
![Screenshot 2024-09-20 142433](https://github.com/user-attachments/assets/c19f4932-1d2f-42b7-8892-64d0d1499e65)
Also attaching my configuration file.
[czertainly-values-custom.zip](https://github.com/user-attachments/files/17073535/czertainly-values-custom.zip)

**Comment by 3keyroman** [comment]
Hello @iftikharahmd , I was looking into your `values.yaml` that you have shared. Assuming that you are using Helm chart version `2.13.0`,  some containers are overwritten by you configuration, for example, you have:
```
image:
  # default registry name
  registry: docker.io
  repository: 3keycompany
  name: czertainly-core
  tag: 2.11.0
```

The default values in Helm chart `2.13.0` are:
```
image:
  # default registry name
  registry: docker.io
  repository: czertainly
  name: czertainly-core
  tag: 2.13.0
```

Effectively, you are overwriting the values with `czertainly-core` container version `2.11.0`, introducing incompatibility in your environment. And this is probably the cause of your issues.

I would recommend you to restore your database back to version `2.11.0`, and then upgrade to version `2.13.0` with proper configuration in `values.yaml`. Or you can update the `values.yaml` without restoring previous version, but I am not sure if all the data will be ok, you can try.
